### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by worblehat** [jxnblk/Heather#1]
Hi Brent,

I really like your theme. I just started to create [my own Github Page](http://worblehat.github.io) using Heather. As you can see I modified it a bit, so I wonder if your code is under a license that permits modification and redistribution. So far I just mentioned Heather in the footer of my site. Are you okay with this?

**Comment by jxnblk** [comment]
Totally fine. And no need to list the theme if you don't want to. I'll add an open source license to clarify

**Comment by worblehat** [comment]
Alright. Thanks for the geat work!
